experiment_name: 2024-04-26-ablation-study

ranges_baran:
  feature_generators:
    - - auto_instance
      - fd
      - llm_correction
      - llm_master
    - - fd
      - llm_correction
      - llm_master
    - - auto_instance
      - llm_correction
      - llm_master
    - - auto_instance
      - fd
      - llm_master
    - - auto_instance
      - fd
      - llm_correction
    - - auto_instance
    - - fd
    - - llm_correction
    - - llm_master

config_baran:
  dataset: "ncvoters"
  n_rows: 70000
  error_fraction: 0
  error_class: "simple_mcar"
  labeling_budget: 20
  synth_tuples: 100
  auto_instance_cache_model: true
  clean_with_user_input: true
  gpdep_threshold: 0.3
  training_time_limit: 600
  llm_name_corrfm: gpt-3.5-turbo
  feature_generators:
    - fd
  classification_model: "ABC"
  vicinity_orders:
    - 1
  vicinity_feature_generator: "naive"
  n_best_pdeps: 3
  synth_cleaning_threshold: 0.9
  test_synth_data_direction: "user_data"
  pdep_features:
    - pr
  fd_feature: "norm_gpdep"
  sampling_technique: "greedy"
  detection_mode: "perfect"
  labeling_error_pct: 0

runs: 3
