experiment_name: 2025-03-04-scalability-rows

ranges_baran:
  n_rows:
    - 5000
    - 10000
    - 15000
    - 20000
    - 25000

config_baran:
  dataset: "ncvoters"
  n_rows: null
  error_fraction: 2
  error_class: "simple_mcar"
  labeling_budget: 20
  synth_tuples: 100
  auto_instance_cache_model: false
  clean_with_user_input: true
  gpdep_threshold: 0.3
  training_time_limit: 300
  llm_name_corrfm: gpt-3.5-turbo
  feature_generators:
    - auto_instance
    - fd
    - llm_correction
    - llm_master
  classification_model: "ABC"
  vicinity_orders:
    - 1
  vicinity_feature_generator: "naive"
  n_best_pdeps: 3
  synth_cleaning_threshold: 0.9
  test_synth_data_direction: "user_data"
  pdep_features:
    - pr
  fd_feature: "norm_gpdep"
  sampling_technique: "greedy"
  detection_mode: "perfect"
  labeling_error_pct: 0

runs: 3
